### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CaviarChen** [websentry/WebSentry#1]
## WebSentry

- [x] Logo
- [ ] Server side i18n&l10n
- [ ] Handle extreme long pages
- [x] Security improvement (limit request rate)
- [ ] Improve code quality
- [ ] Doc
- [ ] Statistic
#### Notification
- [x] Mail support
- [ ] Telegram support

## WebSentry-Frontend

- [ ] First working version

## WebSentry-Slave
